import Head from "next/head";
import { MainPage } from "../components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Thành phố khởi nghiệp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainPage />
    </>
  );
}
